// Copyright 2026 opendbx contributors. See LICENSE.
//
// Author: sqlrush
//
//go:build ignore

// gen-error-codes generates docs/error-codes.md from the live errcode
// registry. spec-0.6 D-6.
//
// Usage:
//
//	go run cmd/tools/gen-error-codes/main.go --out=../opendbrb/docs/error-codes.md
//
// This is intentionally NOT a `go test` target — go test should never write
// to a sibling repo. The Makefile target `make gen-docs` invokes this tool.
//
// claude HIGH-2 R2 — moves cross-repo write out of test scope.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	// Side-effect imports: load every package that calls errcode.Register
	// so the registry is populated before we read it.
	_ "github.com/sqlrush/opendbx/internal/entrypoints"
	"github.com/sqlrush/opendbx/internal/platform/errcode"
	_ "github.com/sqlrush/opendbx/internal/platform/logger"

	_ "github.com/sqlrush/opendbx/internal/platform/config"
	_ "github.com/sqlrush/opendbx/internal/platform/version" // spec-0.7 D-1
)

func main() {
	out := flag.String("out", "", "output path (stdout if empty)")
	flag.Parse()

	var sb strings.Builder
	sb.WriteString("# opendbx error codes\n\n")
	sb.WriteString("> Auto-generated by `cmd/tools/gen-error-codes`; do not edit by hand.\n")
	sb.WriteString("> Source of truth: `internal/platform/<pkg>/errors.go` + `internal/platform/errcode/builtin.go`.\n")
	sb.WriteString("> Spec: `opendbrb/specs/stage-0/spec-0.6-error-codes.md`.\n")
	sb.WriteString(fmt.Sprintf("> Generated: %s UTC\n\n", time.Now().UTC().Format("2006-01-02 15:04")))

	defs := errcode.All()
	if len(defs) == 0 {
		sb.WriteString("_(no codes registered yet)_\n")
	} else {
		// Group by Module.
		byModule := map[string][]errcode.Definition{}
		modules := make([]string, 0)
		for _, def := range defs {
			if _, seen := byModule[def.Module]; !seen {
				modules = append(modules, def.Module)
			}
			byModule[def.Module] = append(byModule[def.Module], def)
		}
		for _, m := range modules {
			sb.WriteString(fmt.Sprintf("## %s\n\n", m))
			sb.WriteString("| Code | Message | Hint |\n|---|---|---|\n")
			for _, def := range byModule[m] {
				sb.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n",
					def.Code, escape(def.Message), escape(def.Hint)))
			}
			sb.WriteString("\n")
		}
	}

	content := sb.String()

	if *out == "" {
		fmt.Print(content)
		return
	}
	if err := os.WriteFile(*out, []byte(content), 0o644); err != nil { //nolint:gosec // spec-0.6 D-6: operator-supplied output path
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *out, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d codes)\n", *out, len(defs))
}

// escape pipes inside markdown table cells.
func escape(s string) string {
	return strings.ReplaceAll(s, "|", `\|`)
}
