// Copyright 2026 opendbx contributors. See LICENSE.
//
// Author: sqlrush

// JSON Schema output (spec-0.4 D-8). Used by `opendbx admin config dump-schema`
// for IDE autocomplete + drift detection.
//
// Stage-0 ships a minimal Draft-07-compatible schema generator (no $ref / no
// allOf / no enum unless validate:"oneof=" is present). spec-0.10 may swap
// in a fuller generator if specific IDE integrations need it.

package config

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"time"
)

// SchemaJSON returns a JSON Schema (Draft-07) describing Config.
func SchemaJSON() ([]byte, error) {
	schema := generateSchema(reflect.TypeOf(Config{}))
	schema["$schema"] = "http://json-schema.org/draft-07/schema#"
	schema["title"] = "opendbx Config"
	schema["description"] = "Generated by opendbx admin config dump-schema (spec-0.4 D-8)"
	return json.MarshalIndent(schema, "", "  ")
}

func generateSchema(t reflect.Type) map[string]any {
	switch t.Kind() {
	case reflect.Struct:
		return structSchema(t)
	case reflect.Slice:
		return map[string]any{
			"type":  "array",
			"items": generateSchema(t.Elem()),
		}
	case reflect.String:
		return map[string]any{"type": "string"}
	case reflect.Bool:
		return map[string]any{"type": "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		// time.Duration is int64 but we render as string per yaml.v3 marshal style.
		if t == reflect.TypeOf(time.Duration(0)) {
			return map[string]any{"type": "string", "format": "duration",
				"description": "Go time.Duration string (e.g. \"30s\", \"5m\")"}
		}
		return map[string]any{"type": "integer"}
	case reflect.Float32, reflect.Float64:
		return map[string]any{"type": "number"}
	default:
		return map[string]any{"type": "object"}
	}
}

func structSchema(t reflect.Type) map[string]any {
	props := make(map[string]any)
	required := []string{}
	for i := 0; i < t.NumField(); i++ {
		ft := t.Field(i)
		if !ft.IsExported() {
			continue
		}
		yamlTag := ft.Tag.Get("yaml")
		if yamlTag == "-" {
			continue
		}
		name := ft.Name
		if yamlTag != "" {
			parts := strings.Split(yamlTag, ",")
			if parts[0] != "" {
				name = parts[0]
			}
		}
		field := generateSchema(ft.Type)
		// Inject validation hints into schema.
		if v := ft.Tag.Get("validate"); v != "" {
			injectValidate(field, v)
			if strings.Contains(v, "required") {
				required = append(required, name)
			}
		}
		if env := ft.Tag.Get("env"); env != "" {
			field["x-env"] = env
		}
		if ft.Tag.Get("redact") == "true" {
			field["x-redact"] = true
		}
		props[name] = field
	}
	out := map[string]any{
		"type":       "object",
		"properties": props,
	}
	if len(required) > 0 {
		out["required"] = required
	}
	return out
}

func injectValidate(field map[string]any, validate string) {
	for _, rule := range strings.Split(validate, ",") {
		rule = strings.TrimSpace(rule)
		switch {
		case strings.HasPrefix(rule, "min="):
			if n, err := parseNum(rule[len("min="):]); err == nil {
				if field["type"] == "string" {
					field["minLength"] = n
				} else {
					field["minimum"] = n
				}
			}
		case strings.HasPrefix(rule, "max="):
			if n, err := parseNum(rule[len("max="):]); err == nil {
				if field["type"] == "string" {
					field["maxLength"] = n
				} else {
					field["maximum"] = n
				}
			}
		case strings.HasPrefix(rule, "oneof="):
			vals := strings.Fields(rule[len("oneof="):])
			out := make([]any, len(vals))
			for i, v := range vals {
				out[i] = v
			}
			field["enum"] = out
		}
	}
}

func parseNum(s string) (float64, error) {
	var n float64
	_, err := fmt.Sscanf(s, "%f", &n)
	return n, err
}
