// Copyright 2026 opendbx contributors. See LICENSE.
//
// Author: sqlrush
//
// paint-pattern-lint enforces the spec-1.20.2 D-3 contract: production
// code MUST NOT write cells from one buffer to another via the bare
//
//	dst.SetCell(x, y, src.Cell(a, b))
//
// pattern, NOR the one-hop equivalent
//
//	c := src.Cell(a, b)
//	dst.SetCell(x, y, c)
//
// because dst.SetCell auto-writes the continuation for a wide-main and
// re-writing the continuation directly triggers Grid.clearWideOverlap,
// shredding the wide-main at (x-1). The fix is to use
// internal/app/cli/render/paint helpers (Blit / BlitAt) which enforce
// the continuation skip, or to guard the same pattern with a
// buffer.IsContinuation(c) → continue/break/return check.
//
// Detection is type-aware (the SetCell receiver must resolve to a
// *render/buffer.Grid and the Cell call must return buffer.Cell) and
// includes one-hop local dataflow inside a single function. Exemptions:
//
//   - package internal/app/cli/render/paint (helper definition)
//   - package internal/app/cli/render/buffer (Grid.SetCell internals
//     and self-tests)
//   - same-receiver read/modify/write (e.g. g.SetCell(x, y, g.Cell(x, y)))
//   - test files (*_test.go) UNLESS the file head carries
//     // paint-pattern-lint:include — production fixture marker
//   - any violation line with a // paint-pattern-lint:exempt --
//     spec-X.Y D-N: <reason> directive on the same line or up to two
//     lines above (mirrors errcode-lint's hasExemptComment proximity).

package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"io"
	"os"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

// DefaultBufferPkgPath is the production import path for the buffer
// package whose Grid.SetCell / Buffer.Cell / IsContinuation symbols this
// lint targets. Tests parameterize it to point at a fake fixture module.
const DefaultBufferPkgPath = "github.com/sqlrush/opendbx/internal/app/cli/render/buffer"

// Violation is one paint-pattern-lint finding.
type Violation struct {
	Pkg      string
	File     string
	Line     int
	Function string
	Kind     string // "direct" or "one-hop"
	Receiver string // dst receiver expression text
	Source   string // src receiver expression text (the .Cell() callee)
}

func (v Violation) String() string {
	return fmt.Sprintf("[PAINT-1] %s:%d %s.%s — bare cell-to-cell copy (%s pattern: %s.SetCell ← %s.Cell); use paint.Blit/BlitAt or add buffer.IsContinuation guard",
		v.File, v.Line, v.Pkg, v.Function, v.Kind, v.Receiver, v.Source)
}

// exemptPkgs returns the set of import paths whose SetCell pattern is
// the contract itself (the helper) or the Grid's internal/test code,
// derived from bufferPath so fixture tests with a fake module path
// still exempt the right packages.
func exemptPkgs(bufferPath string) map[string]bool {
	prefix := strings.TrimSuffix(bufferPath, "/buffer")
	return map[string]bool{
		prefix + "/paint": true,
		bufferPath:        true,
	}
}

// Lint scans the given packages and returns sorted violations.
// bufferPath is the import path of the buffer package whose
// Grid/Cell/IsContinuation API the lint targets. Pass
// DefaultBufferPkgPath in production.
func Lint(dir string, patterns []string, bufferPath string) ([]Violation, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax |
			packages.NeedTypes | packages.NeedTypesInfo | packages.NeedDeps |
			packages.NeedImports | packages.NeedModule,
		// Tests enabled so _test.go files carrying a
		// paint-pattern-lint:include directive can be scanned; files
		// without the directive are filtered in inspectPackage.
		Tests: true,
		Dir:   dir,
	}
	pkgs, err := packages.Load(cfg, patterns...)
	if err != nil {
		return nil, fmt.Errorf("load packages: %w", err)
	}
	exempt := exemptPkgs(bufferPath)
	var all []Violation
	for _, p := range pkgs {
		if len(p.Errors) > 0 {
			for _, e := range p.Errors {
				_, _ = fmt.Fprintf(os.Stderr, "paint-pattern-lint: load error in %s: %s\n", p.PkgPath, e)
			}
		}
		if exempt[p.PkgPath] {
			continue
		}
		// Skip the synthesized test main package (e.g. "pkg.test")
		// generated by Tests:true. Its single Go file is a go-build
		// cache shim that re-exports tests — not real source.
		if strings.HasSuffix(p.PkgPath, ".test") {
			continue
		}
		all = append(all, inspectPackage(p, bufferPath)...)
	}
	sort.Slice(all, func(i, j int) bool {
		if all[i].File != all[j].File {
			return all[i].File < all[j].File
		}
		return all[i].Line < all[j].Line
	})
	return all, nil
}

func inspectPackage(p *packages.Package, bufferPath string) []Violation {
	var out []Violation
	for _, file := range p.Syntax {
		// Always derive path from Fset so _test.go files load via the
		// virtual [pkg.test] package report the right filename
		// (p.GoFiles ordering does not align with p.Syntax for those).
		path := p.Fset.Position(file.Pos()).Filename
		if strings.HasSuffix(path, "_test.go") && !fileHasIncludeDirective(file) {
			continue
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Body == nil {
				continue
			}
			vs := inspectFunc(p, file, fn, bufferPath)
			for j := range vs {
				vs[j].Pkg = p.PkgPath
				vs[j].File = path
				vs[j].Function = funcName(fn)
			}
			out = append(out, vs...)
		}
	}
	return out
}

func funcName(fn *ast.FuncDecl) string {
	if fn.Recv != nil && len(fn.Recv.List) > 0 {
		recv := exprText(fn.Recv.List[0].Type)
		return recv + "." + fn.Name.Name
	}
	return fn.Name.Name
}

// fileHasIncludeDirective looks for a `// paint-pattern-lint:include`
// comment in the file's leading comment groups — used to opt a test
// file into the linter (production fixtures inside _test.go).
func fileHasIncludeDirective(file *ast.File) bool {
	for _, cg := range file.Comments {
		// Stop scanning once we pass the first declaration's start.
		if len(file.Decls) > 0 && cg.Pos() > file.Decls[0].Pos() {
			break
		}
		for _, c := range cg.List {
			// Match only the canonical directive form, not prose that
			// happens to mention the token (e.g. package doc explaining
			// the opt-in). Accept `// paint-pattern-lint:include ...`
			// with the directive immediately after the comment marker.
			body := strings.TrimSpace(strings.TrimPrefix(strings.TrimPrefix(c.Text, "//"), "/*"))
			if strings.HasPrefix(body, "paint-pattern-lint:include") {
				return true
			}
		}
	}
	return false
}

// taint tracks an identifier sourced from `X.Cell(...)`.
type taint struct {
	pos    token.Pos // position of the assigning statement
	source string    // text of X (the source receiver)
}

// inspectFunc walks one function body looking for violations.
func inspectFunc(p *packages.Package, file *ast.File, fn *ast.FuncDecl, bufferPath string) []Violation {
	tinfo := p.TypesInfo
	var out []Violation

	// Per-function tainted variable map. cleared when a buffer.IsContinuation
	// check on the same ident exits the surrounding flow (continue/break/return).
	tainted := map[string]taint{}

	// Statement-by-statement walk, in source order. We use ast.Inspect to
	// descend into nested blocks but track ordering via positions; this is
	// good enough for the patterns this lint targets (assignment, IfStmt
	// guards, and SetCell calls in the same function body).
	ast.Inspect(fn.Body, func(n ast.Node) bool {
		switch s := n.(type) {
		case *ast.AssignStmt:
			handleAssign(s, tinfo, tainted, bufferPath)
		case *ast.IfStmt:
			handleIsContinuationGuard(s, tainted)
		case *ast.CallExpr:
			if v, ok := checkSetCellCall(s, file, p.Fset, tinfo, tainted, bufferPath); ok {
				out = append(out, v)
			}
		}
		return true
	})
	return out
}

// handleAssign records taint for `name := X.Cell(args)` style assignments
// (single LHS, single RHS call returning buffer.Cell).
func handleAssign(s *ast.AssignStmt, tinfo *types.Info, tainted map[string]taint, bufferPath string) {
	if len(s.Lhs) != 1 || len(s.Rhs) != 1 {
		return
	}
	id, ok := s.Lhs[0].(*ast.Ident)
	if !ok {
		return
	}
	call, ok := s.Rhs[0].(*ast.CallExpr)
	if !ok {
		return
	}
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "Cell" {
		return
	}
	if !returnsBufferCell(call, tinfo, bufferPath) {
		return
	}
	tainted[id.Name] = taint{pos: s.Pos(), source: exprText(sel.X)}
}

// handleIsContinuationGuard detects an `if buffer.IsContinuation(c) { ... }`
// where the then-block contains a control-flow exit (continue/break/return).
// The named identifier is removed from `tainted`.
func handleIsContinuationGuard(s *ast.IfStmt, tainted map[string]taint) {
	if s.Cond == nil || s.Body == nil {
		return
	}
	call, ok := s.Cond.(*ast.CallExpr)
	if !ok {
		return
	}
	if !isBufferIsContinuationCall(call) || len(call.Args) != 1 {
		return
	}
	id, ok := call.Args[0].(*ast.Ident)
	if !ok {
		return
	}
	if !bodyExits(s.Body) {
		return
	}
	delete(tainted, id.Name)
}

func bodyExits(b *ast.BlockStmt) bool {
	for _, stmt := range b.List {
		switch v := stmt.(type) {
		case *ast.BranchStmt:
			if v.Tok == token.CONTINUE || v.Tok == token.BREAK || v.Tok == token.GOTO {
				return true
			}
		case *ast.ReturnStmt:
			return true
		}
	}
	return false
}

// checkSetCellCall examines one call expression. Returns (Violation, true)
// if the call is `dst.SetCell(...)` with a cross-receiver Cell-sourced
// argument that lacks a guard.
func checkSetCellCall(call *ast.CallExpr, file *ast.File, fset *token.FileSet, tinfo *types.Info, tainted map[string]taint, bufferPath string) (Violation, bool) {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "SetCell" {
		return Violation{}, false
	}
	if !isBufferGridReceiver(sel.X, tinfo, bufferPath) {
		return Violation{}, false
	}
	dstText := exprText(sel.X)
	for _, arg := range call.Args {
		// Direct: dst.SetCell(..., src.Cell(...))
		if inner, ok := arg.(*ast.CallExpr); ok {
			innerSel, ok := inner.Fun.(*ast.SelectorExpr)
			if !ok || innerSel.Sel.Name != "Cell" {
				continue
			}
			if !returnsBufferCell(inner, tinfo, bufferPath) {
				continue
			}
			srcText := exprText(innerSel.X)
			if srcText == dstText {
				continue // same-receiver exempt
			}
			if hasExemptComment(file, fset, fset.Position(call.Pos()).Line) {
				continue
			}
			return Violation{
				Line:     fset.Position(call.Pos()).Line,
				Kind:     "direct",
				Receiver: dstText,
				Source:   srcText,
			}, true
		}
		// One-hop: dst.SetCell(..., c) where c was assigned from src.Cell(...)
		if id, ok := arg.(*ast.Ident); ok {
			t, found := tainted[id.Name]
			if !found {
				continue
			}
			if t.source == dstText {
				continue // tainted by same-receiver — exempt
			}
			if hasExemptComment(file, fset, fset.Position(call.Pos()).Line) {
				continue
			}
			return Violation{
				Line:     fset.Position(call.Pos()).Line,
				Kind:     "one-hop",
				Receiver: dstText,
				Source:   t.source,
			}, true
		}
	}
	return Violation{}, false
}

// returnsBufferCell checks whether call's return type is buffer.Cell.
func returnsBufferCell(call *ast.CallExpr, tinfo *types.Info, bufferPath string) bool {
	if tinfo == nil {
		return false
	}
	tv, ok := tinfo.Types[call]
	if !ok || tv.Type == nil {
		return false
	}
	named, ok := tv.Type.(*types.Named)
	if !ok {
		return false
	}
	obj := named.Obj()
	if obj == nil || obj.Name() != "Cell" {
		return false
	}
	return obj.Pkg() != nil && obj.Pkg().Path() == bufferPath
}

// isBufferGridReceiver checks whether expr resolves to *buffer.Grid (or
// buffer.Grid value receiver — same type for method-set purposes).
func isBufferGridReceiver(expr ast.Expr, tinfo *types.Info, bufferPath string) bool {
	if tinfo == nil {
		return false
	}
	tv, ok := tinfo.Types[expr]
	if !ok || tv.Type == nil {
		return false
	}
	t := tv.Type
	if ptr, ok := t.(*types.Pointer); ok {
		t = ptr.Elem()
	}
	named, ok := t.(*types.Named)
	if !ok {
		return false
	}
	obj := named.Obj()
	if obj == nil || obj.Name() != "Grid" {
		return false
	}
	return obj.Pkg() != nil && obj.Pkg().Path() == bufferPath
}

// isBufferIsContinuationCall checks whether call is buffer.IsContinuation(...).
func isBufferIsContinuationCall(call *ast.CallExpr) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "IsContinuation" {
		return false
	}
	id, ok := sel.X.(*ast.Ident)
	if !ok {
		return false
	}
	return id.Name == "buffer"
}

// hasExemptComment scans comment groups above lineN for a
// paint-pattern-lint:exempt directive. Accepts same-line or up to two
// lines above (mirrors errcode-lint).
func hasExemptComment(file *ast.File, fset *token.FileSet, lineN int) bool {
	for _, cg := range file.Comments {
		for _, c := range cg.List {
			if !strings.Contains(c.Text, "paint-pattern-lint:exempt") {
				continue
			}
			pos := fset.Position(c.Pos())
			if pos.Line == lineN || pos.Line == lineN-1 || pos.Line == lineN-2 {
				return true
			}
		}
	}
	return false
}

// exprText prints an expression as Go source text (best effort). Used
// for receiver comparison and human-readable Violation output.
func exprText(e ast.Expr) string {
	switch v := e.(type) {
	case *ast.Ident:
		return v.Name
	case *ast.SelectorExpr:
		return exprText(v.X) + "." + v.Sel.Name
	case *ast.StarExpr:
		return "*" + exprText(v.X)
	case *ast.IndexExpr:
		return exprText(v.X) + "[" + exprText(v.Index) + "]"
	case *ast.ParenExpr:
		return "(" + exprText(v.X) + ")"
	default:
		return "?"
	}
}

// realMain wraps flag parsing for test coverage.
func realMain(args []string, w io.Writer) int {
	fs := flag.NewFlagSet("paint-pattern-lint", flag.ContinueOnError)
	fs.SetOutput(w)
	verbose := fs.Bool("v", false, "verbose: print scanned package count")
	dir := fs.String("dir", "", "working directory for package loading (default cwd)")
	bufferPkg := fs.String("bufferpkg", DefaultBufferPkgPath,
		"import path of the buffer package whose Grid/Cell/IsContinuation API to check (tests override; production keeps default)")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	patterns := fs.Args()
	if len(patterns) == 0 {
		patterns = []string{"./..."}
	}
	vs, err := Lint(*dir, patterns, *bufferPkg)
	if err != nil {
		_, _ = fmt.Fprintf(w, "paint-pattern-lint: %v\n", err)
		return 2
	}
	if *verbose {
		_, _ = fmt.Fprintf(w, "paint-pattern-lint: scanned patterns %v; %d violation(s)\n",
			patterns, len(vs))
	}
	if len(vs) == 0 {
		_, _ = fmt.Fprintln(w, "paint-pattern-lint OK: no bare cell-to-cell SetCell patterns found")
		return 0
	}
	_, _ = fmt.Fprintf(w, "paint-pattern-lint FAIL: %d violation(s)\n", len(vs))
	for _, v := range vs {
		_, _ = fmt.Fprintln(w, v)
	}
	_, _ = fmt.Fprintln(w, "hint: use internal/app/cli/render/paint.Blit / BlitAt (spec-1.20.2 D-1 contract)")
	_, _ = fmt.Fprintln(w, "      to suppress: // paint-pattern-lint:exempt -- spec-X.Y D-N: <reason>")
	return 1
}

func main() {
	os.Exit(realMain(os.Args[1:], os.Stderr))
}
